# ===================================
#  Relation Behavior Config
# ===================================

locations:
    label: 'Location'
    view:
        list: $/albrightlabs/clientlocations/models/location/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/albrightlabs/clientlocations/models/location/fields.yaml
        recordsPerPage: 10
